### PR TITLE
Fix export format so it is in valid ESM syntax

### PR DESCRIPTION
**Pull request by minlite**
Sending another PR because I realized the definitions in `index.d.ts` don't actually match the export syntax in `index.js`.

This commit correctly exports the functions in `index.js` in ESM format so they can be used in typescript or javascript like below:

```typescript
import { whash } from 'imagehash-web';
```

### CODE REVIEW

**Comment by minlite** [comment]
There also seems to be another issue where `parcel build` builds browser specific bundle and causes node to incorrectly use the browser specific version of `canvas`. Looking into this now.

**Comment by minlite** [comment]
Should be ready. I added parcel targets for node and changed the main in `package.json` to point to it since that is what node uses when you require a package. The browser bundle and its minified version are still being built correctly and can be used as before.

**Comment by simon987** [comment]
Thank you, out of curiosity have you been able to make the example browser usage work _on Chrome_? Looks like they changed something in the current version because I see this error now

```html
<html>

<body>
    <img src="./test_fixtures/100px.jpg" id="my-image">

    <script src="./dist/imagehash-web.min.js"></script>
    <script>
        window.setTimeout(function() {
            const im = document.getElementById("my-image");

            const precomputed = ImageHash.fromHexString("5dbfb5310a81a361")

            phash(im, 8).then(hash => {
                console.log(hash.hammingDistance(precomputed));
            });
        }, 400)
    </script>
</body>

</html>

```

```
Uncaught (in promise) IndexSizeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at R.__extractTileData (imagehash-web.min.js:1:27509)
    at imagehash-web.min.js:1:29055
```

**Comment by minlite** [comment]
I'm getting the same error. I'll look into it later today

**Comment by minlite** [comment]
Good news, I was able to pin point the issue. 

In `imageUtils.js` function `resizeImage`, when you do the following, it causes a reload of the image:

```
 if (typeof window !== "undefined") {
     image.setAttribute("crossOrigin", "Anonymous");
 }
```

Therefore when calculating the `fromCanvas` in the next line, the image has still not loaded and has 0 width and height, causing the division by zero error.

What was the reasoning for setting the `crossOrigin` attribute and do we still need it? I commented it out and the code works fine without it.

**Comment by simon987** [comment]
Honestly I can't remember why this was added, but if it works without I think it's fine, thanks so much for investigating!

**Pull request merged**
